# fly.toml app configuration file generated for whack-a-bevy on 2024-04-01T22:38:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whack-a-bevy'
primary_region = 'cdg'

[build]

[http_service]
internal_port = 8083
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
