[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.example-web]
workspace = false
script = '''
cd crates/example_client_web && wasm-pack build --target web --out-dir public/pkg
'''

[tasks.w]
workspace = false
dependencies = ["example-web"]
env = { CARGO_MAKE_SCRIPT_FORCE_PIPE_STDIN = true }
script = '''
cd crates/example_client_web/public && basic-http-server
'''